import{a as k}from"../chunks/chunk-T6N25VDY.js";import{a as V}from"../chunks/chunk-RQD6OPCK.js";import{F as R,K as f,X as B,o as C}from"../chunks/chunk-XRJW3LFT.js";import"../chunks/chunk-5LUD7HVS.js";import"../chunks/chunk-K3HP5COO.js";import{a as b}from"../chunks/chunk-ZL5H3TML.js";import"../chunks/chunk-523WHQDT.js";import{a as n}from"../chunks/chunk-MV4HDL2S.js";import"../chunks/chunk-6OCQJS5B.js";import{a as v}from"../chunks/chunk-2MCFUH3Z.js";import"../chunks/chunk-5Q7VJYCY.js";import"../chunks/chunk-X7CFCWZC.js";import{a as P}from"../chunks/chunk-XEDCPNRR.js";import"../chunks/chunk-BCG2KUGW.js";import"../chunks/chunk-YZTZIJSB.js";import"../chunks/chunk-YU5QULAP.js";import"../chunks/chunk-VGIBV4EV.js";import"../chunks/chunk-IYAFYZRF.js";import"../chunks/chunk-F2BE3OL5.js";import"../chunks/chunk-65VGUSSD.js";import{a as y}from"../chunks/chunk-O7OTS7RM.js";import"../chunks/chunk-2SFZECRB.js";import"../chunks/chunk-D2CCZ3BJ.js";import"../chunks/chunk-7YV4JAJK.js";import"../chunks/chunk-KZL57NC7.js";import{a as h,b as g,c as a,e as I,l as w,r as S,v as A}from"../chunks/chunk-R5NGUZ66.js";import"../chunks/chunk-O4TFJKJQ.js";import{c as e,k as l,m as c,u}from"../chunks/chunk-JJTF2C25.js";import"../chunks/chunk-6LTHT6DZ.js";import"../chunks/chunk-NYTRMFGH.js";import"../chunks/chunk-HY2GWXPO.js";import"../chunks/chunk-JV3JVBWM.js";import{c as F}from"../chunks/chunk-3HBOA5LN.js";import"../chunks/chunk-4NTWQHWX.js";import"../chunks/chunk-YHJJDH4X.js";import{e as r}from"../chunks/chunk-3GYLW4KZ.js";var it=r(h()),U=r(F());var D=r(h());var s=r(I());var _=r(P()),L=(0,s.default)(w).attrs(({hasActivated:t})=>({backgroundColor:t?"objectFavorableEmphasisHigh":void 0,fontSize:"medium",sizeType:"large"}))`
  ${({hasActivated:t,theme:o})=>(0,_.cssNamespace)(s.css`
      cursor: ${t?"default":void 0};

      &:hover {
        background-color: ${t?o.colors.objectFavorableEmphasisHigh:void 0};
      }
    `)};
`;var m=r(a()),$=({isActivating:t,hasActivated:o})=>((0,D.useEffect)(()=>{u("page","cashbackAnnotation")},[]),(0,m.jsxs)(L,{hasActivated:o,isLoading:!o&&t,onClick:!o&&!t?async()=>{if(!f()){let{session:x}=await n();e.set("session",x)}if(!f()){window.open(`${y}/sign-in`);return}e.get("cashbackVisible")?e.set(["cashbackView","autoActivate"],!0):B(e.get("deweyResult"),{autoActivate:!0})}:void 0,children:[(0,m.jsx)(k,{fill:"white",width:14,marginRight:8})," ",o?"Rewards Activated":t?"Activating Rewards...":"Activate Rewards"]})),p=g({isActivating:["cashbackView","user","activating"],hasActivated:["cashbackView","user","activated"]},$);var d=r(a()),H=()=>(0,d.jsx)(S,{children:(0,d.jsx)(p,{})});function M(){return U.default.all([n(),v(),R()]).spread((t,o,i)=>{V(t),e.merge({siteAPIData:o}),e.merge({cashbackView:i})})}var q=async(t,o)=>(await M(),(!e.get("cashbackView")||C())&&!e.get("hasActivatedCompetitor")?!1:(A({app:H(),blankSlate:!0,insertAfterElement:o}),!0));function E(){if(!c("ext_shopify_cta"))return;let t=l(),o=c("ext_separate_domain_platform")?e.get("platform")==="Shopify":b(t),i;o&&(i=document.querySelector(".order-summary__section--total-lines")||document.querySelector("[aria-labelledby=MoneyLine-Heading0]")),i&&q(t,i)}document.readyState!=="loading"?E():document.addEventListener("DOMContentLoaded",E);
