var ttsEngine=document.getElementById("tts-engine"),ttsRate=document.getElementById("tts-rate"),ttsRateIndi=document.getElementById("tts-rate-indicator"),ttsVolume=document.getElementById("tts-volume"),ttsVolumeIndi=document.getElementById("tts-volume-indicator"),ttsTestContent=document.getElementById("tts-test-text"),ttsPlay=document.getElementById("tts-play"),ttsSave=document.getElementById("tts-save"),ttsSaved=document.getElementById("tts-saved"),hour12=document.getElementById("hour12"),hour24=
document.getElementById("hour24"),alarmEnable=document.getElementById("enable-alarm"),timeSettings=document.getElementById("time-settings"),popupClockDigital=document.getElementById("popup-clock-digital"),popupClockAnalog=document.getElementById("popup-clock-analog"),popupSecond=document.getElementById("popup-second"),popupDate=document.getElementById("popup-date"),popupReminder=document.getElementById("popup-reminder"),shortcuts=document.getElementById("shortcuts"),badgeTime=document.getElementById("badge-time"),
timeVoiceNotify=document.getElementById("time-notify-voice"),timeSystemNotify=document.getElementById("time-notify-system"),timeDndLocked=document.getElementById("dnd-locked"),timeDndFullscreen=document.getElementById("dnd-fullscreen"),timeDndAudible=document.getElementById("dnd-audible"),muteAll=document.getElementById("mute-all"),muteWarning=document.getElementById("mute-warning");
function getTtsOptions(){let a={rate:parseFloat(ttsRate.value),volume:parseFloat(ttsVolume.value)},b=ttsEngine.selectedOptions[0];b.dataset.lang?a.lang=b.dataset.lang:tts.lang=chrome.i18n.getUILanguage();b.dataset.voice&&(a.voiceName=b.dataset.voice);b.dataset.extension&&(a.extensionId=b.dataset.extension);return a}var speaking=!1;
function ttsTest(){if(speaking)speaking=!1,ttsPlay.textContent=chrome.i18n.getMessage("btn_speak"),chrome.tts.stop();else{speaking=!0;ttsPlay.textContent=chrome.i18n.getMessage("btn_stop");let a=getTtsOptions();a.onEvent=function(b){b=b.type;if("end"==b||"interrupted"==b||"cancelled"==b||"error"==b)speaking=!1,ttsPlay.textContent=chrome.i18n.getMessage("btn_speak")};chrome.tts.speak(ttsTestContent.value,a)}}
function setupVoices(a,b){for(var c=new Intl.DisplayNames([],{type:"language",style:"short",languageDisplay:"standard"}),e=0;e<a.length;e++){var d=a[e];d.lang&&(d.langDN=c.of(d.lang))}a.sort(function(f,g){return f.langDN&&g.langDN&&f.langDN!=g.langDN?f.langDN.localeCompare(g.langDN):f.voiceName&&g.voiceName?f.voiceName.localeCompare(g.voiceName):-1});for(e=0;e<a.length;e++){d=a[e];c=createTTSOption(d);if((0==e||a[e-1].lang!=d.lang)&&d.lang){let f=document.createElement("optgroup");f.label=d.langDN;
ttsEngine.appendChild(f)}(d=ttsEngine.lastElementChild)&&"OPTGROUP"==d.tagName?ttsEngine.lastElementChild.appendChild(c):ttsEngine.appendChild(c)}b.tts&&b.tts.voiceName&&(a=ttsEngine.querySelector('option[data-voice="'+b.tts.voiceName+'"]'))&&(a.selected=!0)}
function initTTSEngine(a){chrome.tts.getVoices(function(b){setupVoices(b,a);setTimeout(function(){chrome.tts.getVoices(function(c){b.length!=c.length&&(ttsEngine.innerHTML="",setupVoices(c,a))})},2E3)});a.tts&&(a.tts.volume&&(ttsVolume.value=a.tts.volume,ttsVolumeIndi.textContent=ttsVolume.value),a.tts.rate&&(ttsRate.value=a.tts.rate,ttsRateIndi.textContent=ttsRate.value))}
function createTTSOption(a){let b=document.createElement("option");b.textContent=a.voiceName;a.lang&&(b.dataset.lang=a.lang);a.extensionId&&(b.dataset.extension=a.extensionId);a.voiceName&&(b.dataset.voice=a.voiceName);return b}function saveTtsOption(){let a=getTtsOptions();chrome.storage.local.set({tts:a},function(){ttsSaved.classList.remove("d-none");setTimeout(function(){ttsSaved.classList.add("d-none")},1E3)})}
function updateTimeEnable(){alarmEnable.checked?(chrome.storage.local.set({timeEnabled:!0}),timeSettings.classList.remove("d-none")):(chrome.storage.local.set({timeEnabled:!1}),timeSettings.classList.add("d-none"))}function updateMute(){muteAll.checked?(chrome.storage.local.set({muteAll:!0}),muteWarning.classList.remove("d-none")):(chrome.storage.local.set({muteAll:!1}),muteWarning.classList.add("d-none"))}
function updateTimePeriod(a){a=parseInt(this.value,10);chrome.storage.local.set({timePeriod:a})}function updateHour12(a){chrome.storage.local.set({hour12:"hour12"==this.value})}function updatePopupClock(a){chrome.storage.local.set({popupClock:this.value})}function updatePopupDate(a){chrome.storage.local.set({popupDate:this.checked})}function updatePopupReminder(a){chrome.storage.local.set({popupReminder:this.checked})}
function updatePopupSecond(a){chrome.storage.local.set({popupSecond:this.checked})}function updateBadgeTime(a){chrome.storage.local.set({badgeEnabled:this.checked})}function updateTimeVoiceNotify(a){chrome.storage.local.set({timeVoiceNotify:this.checked})}function updateTimeSystemNotify(a){chrome.storage.local.set({timeSystemNotify:this.checked})}function updateTimeDndLocked(a){chrome.storage.local.set({timeDndLocked:this.checked})}
function updateTimeDndAudible(a){chrome.storage.local.set({timeDndAudible:this.checked})}function updateTimeDndFullscreen(a){chrome.storage.local.set({timeDndFullscreen:this.checked})}function openShortcuts(a){a.preventDefault();a=chrome.i18n.getMessage("extName");a="chrome://extensions/shortcuts#:~:text="+encodeURIComponent(a);chrome.tabs.create({url:a})}
function init(){ttsPlay.addEventListener("click",ttsTest);ttsSave.addEventListener("click",saveTtsOption);ttsVolume.addEventListener("input",function(c){ttsVolumeIndi.textContent=this.value});ttsRate.addEventListener("input",function(c){ttsRateIndi.textContent=this.value});alarmEnable.addEventListener("click",updateTimeEnable);muteAll.addEventListener("click",updateMute);let a=document.querySelectorAll('input[name="alarm-interval"]');for(var b=0;b<a.length;b++)a[b].addEventListener("click",updateTimePeriod);
hour12.addEventListener("click",updateHour12);hour24.addEventListener("click",updateHour12);popupClockAnalog.addEventListener("click",updatePopupClock);popupClockDigital.addEventListener("click",updatePopupClock);popupSecond.addEventListener("click",updatePopupSecond);popupDate.addEventListener("click",updatePopupDate);popupReminder.addEventListener("click",updatePopupReminder);shortcuts.addEventListener("click",openShortcuts);badgeTime.addEventListener("click",updateBadgeTime);timeVoiceNotify.addEventListener("click",
updateTimeVoiceNotify);timeSystemNotify.addEventListener("click",updateTimeSystemNotify);timeDndLocked.addEventListener("click",updateTimeDndLocked);timeDndAudible.addEventListener("click",updateTimeDndAudible);timeDndFullscreen.addEventListener("click",updateTimeDndFullscreen);Task.init();initMsg();document.querySelectorAll("input[type=text]").forEach(c=>c.addEventListener("keydown",preventEnter))}function preventEnter(a){if(13==a.keyCode)return a.preventDefault(),a.stopPropagation(),!1}
function initSettings(a){initTTSEngine(a);void 0===a.timePeriod&&(a.timePeriod=60);document.getElementById("interval-"+a.timePeriod).checked=a.timePeriod;chrome.alarms.get("time",function(b){b?alarmEnable.checked=!0:(alarmEnable.checked=!1,timeSettings.classList.add("d-none"))});chrome.alarms.get("badge",function(b){badgeTime.checked=b?!0:!1});void 0===a.timeDndLocked&&(a.timeDndLocked=!0);timeDndLocked.checked=a.timeDndLocked;void 0===a.timeDndAudible&&(a.timeDndAudible=!0);timeDndAudible.checked=
a.timeDndAudible;void 0===a.timeDndFullscreen&&(a.timeDndFullscreen=!0);timeDndFullscreen.checked=a.timeDndFullscreen;void 0===a.hour12&&(a.hour12=!0);a.hour12?hour12.checked=!0:hour24.checked=!0;void 0===a.popupClock&&(a.popupClock="analog");"digital"==a.popupClock?popupClockDigital.checked=!0:popupClockAnalog.checked=!0;void 0===a.popupDate&&(a.popupDate=!0);popupDate.checked=a.popupDate;void 0===a.popupSecond&&(a.popupSecond=!0);popupSecond.checked=a.popupSecond;void 0===a.popupReminder&&(a.popupReminder=
!0);popupReminder.checked=a.popupReminder;void 0!=a.timeVoiceNotify&&(timeVoiceNotify.checked=a.timeVoiceNotify);void 0!=a.timeSystemNotify&&(timeSystemNotify.checked=a.timeSystemNotify);void 0===a.muteAll&&(a.muteAll=!1);muteAll.checked=a.muteAll;muteAll.checked&&muteWarning.classList.remove("d-none");Task.initTaskList(a);"zh-CN"==lang&&(document.getElementById("tts-hlep-win").href="https://support.office.com/zh-cn/article/%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E9%80%82%E7%94%A8%E4%BA%8E-windows-10-%E7%9A%84%E6%96%87%E6%9C%AC%E5%88%B0%E8%AF%AD%E9%9F%B3%E8%BD%AC%E6%8D%A2%E8%AF%AD%E8%A8%80-d5a6b612-b3ae-423f-afa5-4f6caf1ec5d3",
document.getElementById("tts-hlep-mac").href="https://support.apple.com/zh-cn/guide/mac-help/mchlp2290/mac")}function initMsg(a=document){a=a.querySelectorAll("[data-i18n]");for(const b of a)b.textContent=chrome.i18n.getMessage(b.dataset.i18n)}init();chrome.storage.local.get(null,initSettings);
