var taskRepeatType=document.getElementById("task-repeat"),taskRepeatOnce=document.getElementById("task-repeat-once"),taskRepeatWeek=document.getElementById("task-repeat-week"),taskRepeatMonth=document.getElementById("task-repeat-month"),taskRepeatYear=document.getElementById("task-repeat-year"),taskTimeContainer=document.getElementById("task-time-container"),taskVoiceNotify=document.getElementById("task-notify-voice"),taskSystemNotify=document.getElementById("task-notify-system"),taskNotifyClose=
document.getElementById("task-notify-close"),taskDate=document.getElementById("task-date"),taskList=document.getElementById("task-list"),lang="zh-CN"==chrome.i18n.getUILanguage()?"zh-CN":"en-US";const maxDayInMonth=[31,29,31,30,31,30,31,31,30,31,30,31];
class Task{static updateTaskRepeat(a){const b=[taskRepeatOnce,taskRepeatWeek,taskRepeatMonth,taskRepeatYear];for(var d=0;d<b.length;d++){let c=b[d];c.id.endsWith(a)?c.classList.remove("d-none"):c.classList.add("d-none")}}static addTime(a){let b=document.importNode(document.getElementById("task-time-tp").content,!0);initMsg(b);let d=b.firstElementChild,c=b.querySelector("label"),e=b.querySelector("input"),[f,g]=b.querySelectorAll(".icon-button");const h="task-time-"+Task.idCount++;e.id=h;c.htmlFor=
h;f.addEventListener("click",()=>Task.addTime(d));0==taskTimeContainer.childElementCount?g.remove():(c.textContent="",g.addEventListener("click",function(k){1<taskTimeContainer.childElementCount&&this.closest(".form-group").remove()}));a?a.insertAdjacentElement("afterend",d):taskTimeContainer.appendChild(b)}static addYear(a){let b=document.importNode(document.getElementById("task-year-tp").content,!0);initMsg(b);let d=b.firstElementChild;initMsg(d);let c=b.querySelector("label"),[e,f]=b.querySelectorAll(".icon-button");
e.addEventListener("click",()=>Task.addYear(d));0==taskRepeatYear.childElementCount?f.remove():(c.textContent="",f.addEventListener("click",function(g){1<taskRepeatYear.childElementCount&&this.closest(".form-group").remove()}));a?a.insertAdjacentElement("afterend",d):taskRepeatYear.appendChild(b)}static showForCreate(){Task.edit=void 0;document.querySelector("#task-modal form").reset();document.querySelectorAll("#task-modal .page-item.active").forEach(a=>a.classList.remove("active"));document.querySelectorAll("#task-modal .is-invalid").forEach(a=>
a.classList.remove("is-invalid"));taskNotifyClose.value="1";taskRepeatType.value="day";Task.updateTaskRepeat("day");taskTimeContainer.innerHTML="";Task.addTime();taskRepeatYear.innerHTML="";Task.addYear();$("#task-modal").modal()}static showForUpdate(a){document.querySelector("#task-modal form").reset();document.querySelectorAll("#task-modal .page-item.active").forEach(b=>b.classList.remove("active"));document.querySelectorAll("#task-modal .is-invalid").forEach(b=>b.classList.remove("is-invalid"));
chrome.storage.local.get(a,function(b){if(b=b[a])Task.edit=b,Task.fillForUpdate(b),$("#task-modal").modal()})}static fillForUpdate(a){const b=a.type;taskRepeatType.value=b;Task.updateTaskRepeat(b);taskVoiceNotify.checked=a.voiceNotify;taskSystemNotify.checked=a.systemNotify;document.getElementById("task-input").value=a.text;taskNotifyClose.value=a.notifyClose?a.notifyClose:"1";taskTimeContainer.innerHTML="";a.time.forEach(function(c){Task.addTime();taskTimeContainer.lastElementChild.querySelector("input").value=
Task.timeToStr(c)});if("once"==b)taskDate.value=Task.dateToStr(a.date);else if("week"==b){var d=a.week;for(a=0;a<d.length;a++)document.querySelector(`#task-repeat-week span[data-value="${d[a]}"]`).parentElement.classList.add("active")}else if("month"==b)for(d=a.month,a=0;a<d.length;a++)-1!=d[a]?document.querySelector(`#task-repeat-month span[data-value="${d[a]}"]`).parentElement.classList.add("active"):document.getElementById("task-month-endday").checked=!0;else if("year"==b)for(taskRepeatYear.innerHTML=
"",d=a.year,a=0;a<d.length;a++){Task.addYear();let [c,e]=taskRepeatYear.lastElementChild.querySelectorAll("select");c.value=d[a][0];e.value=d[a][1]}"year"!=b&&(taskRepeatYear.innerHTML="",Task.addYear())}static timeToStr(a){let b=a[0].toString().padStart(2,"0");a=a[1].toString().padStart(2,"0");return`${b}:${a}`}static dateToStr(a){let b=a[0].toString().padStart(4,"0"),d=a[1].toString().padStart(2,"0");a=a[2].toString().padStart(2,"0");return`${b}-${d}-${a}`}static timeStrToArray(a){return a.split(":").map(b=>
parseInt(b,10))}static dateStrToArray(a){return a.split("-").map(b=>parseInt(b,10))}static i18nDateStr(a,b){return"zh-CN"==lang?`${a}\u6708${b}\u65e5`:`${chrome.i18n.getMessage(`month_${a}`)} ${b}`}static i18nTypeDateStr(a,b){a=chrome.i18n.getMessage("repeat_"+a).toLowerCase();a=a.charAt(0).toUpperCase()+a.slice(1);return b?"zh-CN"==lang?`${a} ${b}`:`${a} on ${b}`:a}static i18nDateTimeStr(a,b){return"zh-CN"==lang?`${a} ${b}`:`${a} at ${b}`}static validate(){var a=taskRepeatType.value;let b=!0,d={type:a,
voiceNotify:taskVoiceNotify.checked,systemNotify:taskSystemNotify.checked,notifyClose:taskNotifyClose.value};var c=document.getElementById("task-input"),e=c.value.trim();e?(c.classList.remove("is-invalid"),d.text=e):(c.classList.add("is-invalid"),b=!1);e=taskTimeContainer.querySelectorAll("input");var f=[];for(c=0;c<e.length;c++){var g=e[c];g.value?(g.classList.remove("is-invalid"),f.includes(g.value)||f.push(g.value)):(g.classList.add("is-invalid"),b=!1)}d.time=f.sort().map(Task.timeStrToArray);
if("once"==a)taskDate.value?(taskDate.classList.remove("is-invalid"),d.date=Task.dateStrToArray(taskDate.value)):(taskDate.classList.add("is-invalid"),b=!1);else if("week"==a)if(a=document.querySelectorAll("#task-repeat-week li.active > span"),c=document.querySelector("#task-repeat-week ul"),0==a.length)c.classList.add("is-invalid"),b=!1;else{c.classList.remove("is-invalid");e=[];for(c=0;c<a.length;c++)e.push(parseInt(a[c].dataset.value,10));d.week=e}else if("month"==a)if(a=document.querySelectorAll("#task-repeat-month li.active > span"),
c=document.getElementById("task-month-endday"),e=c.checked,0!=a.length||e){c.parentElement.classList.remove("is-invalid");f=[];for(c=0;c<a.length;c++)f.push(parseInt(a[c].dataset.value,10));e&&f.push(-1);d.month=f}else c.parentElement.classList.add("is-invalid"),b=!1;else if("year"==a){a=[];e=taskRepeatYear.querySelectorAll("select");for(c=0;c<e.length;c+=2){f=e[c];g=e[c+1];let h=parseInt(f.value,10),k=parseInt(g.value,10);k>maxDayInMonth[h-1]?(b=!1,g.nextElementSibling.textContent=chrome.i18n.getMessage("max_day_in_month",
[g.value,f.selectedOptions[0].textContent]),g.classList.add("is-invalid")):(g.classList.remove("is-invalid"),void 0==a.find(l=>l[0]==h&&l[1]==k)&&a.push([h,k]))}d.year=a.sort(function(h,k){const l=h[0]-k[0];return 0!=l?l:h[1]-k[1]})}return b?d:!1}static createTask(){let a=Task.validate();if(a){if(Task.edit)a.id=Task.edit.id,a.enable=Task.edit.enable,a.createTime=Task.edit.createTime;else{a.enable=!0;var b=Date.now();a.createTime=b;a.id="task-"+b.toString(36)}b={};b[a.id]=a;chrome.storage.local.set(b,
function(){chrome.storage.local.get(null,Task.initTaskList)});a.enable&&Task.startTask(a);$("#task-modal").modal("hide")}}static deleteTask(a){chrome.storage.local.remove(a,function(){let b=document.getElementById(a);b&&b.remove()});Task.stopTask(a)}static enableTask(a,b){chrome.storage.local.get(a,function(d){let c=d[a];c?(c.enable=b,chrome.storage.local.set(d),c.enable?Task.startTask(c):Task.stopTask(a)):chrome.storage.local.get(null,Task.initTaskList)})}static startTask(a){chrome.runtime.sendMessage({type:"StartTask",
task:a})}static stopTask(a){chrome.alarms.clear(a)}static descTask(a){var b=a.type;if("once"==b){b=a.date;var d=(new Date(b[0],b[1]-1,b[2])).toLocaleDateString(lang,{dateStyle:"medium"})}else if("day"==b)d=Task.i18nTypeDateStr(b);else if("week"==b){var c=a.week.map(f=>chrome.i18n.getMessage("week_"+f));d=Task.i18nTypeDateStr(b,c.join(", "))}else if("month"==b)c=a.month.map(f=>-1==f?(f=chrome.i18n.getMessage("month_end").toLowerCase(),1<a.month.length&&(f="zh-CN"==lang?"\u548c"+f:"and "+f),f):f),d=
Task.i18nTypeDateStr(b,c.join(", "));else if("year"==b){d=a.year;var e=[];for(c=0;c<d.length;c++)e.push(Task.i18nDateStr(d[c][0],d[c][1]));d=Task.i18nTypeDateStr(b,e.join(", "))}b=[];e=a.time;for(c=0;c<e.length;c++)b.push(Task.timeToStr(e[c]));return Task.i18nDateTimeStr(d,b.join(", "))}static isExpired(a){let b=!0;var d=a.date;d=new Date(d[0],d[1]-1,d[2]);a=a.time;const c=Date.now();for(var e=0;e<a.length;e++)if(d.setHours(a[e][0],a[e][1],0,0),d.getTime()>c){b=!1;break}return b}static addTaskItem(a){let b=
document.importNode(document.getElementById("task-item-tp").content,!0);b.firstElementChild.id=a.id;b.querySelector("h4").textContent=a.text;var d=b.querySelector(".task-desc");d.textContent=Task.descTask(a);if("once"==a.type&&Task.isExpired(a)){let e=document.createElement("span");e.className="badge badge-secondary align-text-top";e.textContent=chrome.i18n.getMessage("reminder_expired");d.textContent+=" ";d.appendChild(e)}d=a.id+"-input";let c=b.querySelector(".custom-control-input");c.id=d;c.checked=
a.enable;c.addEventListener("click",function(){Task.enableTask(a.id,c.checked)});b.querySelector(".custom-control-label").htmlFor=d;b.querySelector(".btn-primary").addEventListener("click",function(){Task.showForUpdate(a.id)});b.querySelector(".btn-danger").addEventListener("click",function(){Task.deleteTask(a.id)});initMsg(b);taskList.appendChild(b)}static initTaskList(a){taskList.innerHTML="";let b=[];for(let [d,c]of Object.entries(a))d.startsWith("task-")&&b.push(c);b.sort((d,c)=>d.createTime-
c.createTime).forEach(Task.addTaskItem)}static init(){taskRepeatType.addEventListener("change",function(d){Task.updateTaskRepeat(this.value)});document.getElementById("task-save").addEventListener("click",Task.createTask);document.getElementById("task-add").addEventListener("click",Task.showForCreate);let a=document.querySelectorAll("#task-repeat-week li,#task-repeat-month li");for(var b=0;b<a.length;b++)a[b].addEventListener("click",function(){this.classList.toggle("active")})}}Task.idCount=0;
